accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
    path('profile/<username>/', views.Profile.as_view(), name="profile")

    # path('password_change/', name="password_change"),
    # path('password_change/done', name="password_change_done"),
    # path('password_reset/', name='password_reset'),
    # path('reset/<uidb64>/<token>/', name="password_reset_confirm"),
    # path('reset/', name="password_reset_complete")
]

charity/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.HomePage.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('posts/', include("posts.urls", namespace="posts")),
    path('secureLogout/', views.LogoutPage.as_view(), name="logout"),
    path('secureLogin/', views.LoginPage.as_view(), name="login"),
    path('session-expired/', views.session_expired, name='session_expired'),
]

posts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name="all"),
    path("new/", views.create_post, name="create"),
    path("by/<username>/",views.user_posts,name="for_user"),
    path("by/<username>/<int:pk>/",views.post_detail,name="single"),
    path("delete/<int:pk>/",views.delete_post,name="delete"),
]

templates/after_login.html
{% extends 'base.html' %}
{% block content %}
<h1>You are now logged in!</h1>
{% endblock %}

templates/after_logout.html
{% extends 'base.html' %}
{% block content %}
<h1>Thanks for visiting!</h1>
{% endblock %}

templates/base.html
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Charity</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Alternative to Bootstrap 3 Glyphicons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static '/css/master.css'%}">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'home' %}">Charity</a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated%}
                <li><a class="nav-item nav-link btn btn-simple" href="{% url 'posts:create' %}">Create Post</a></li>
                <li><a class="nav-item nav-link btn btn-simple" href="{% url 'posts:all' %}">Post</a></li>
                <li><a class="nav-item nav-link btn btn-simple" href="{% url 'accounts:profile'%}">Profile</a></li>
                <li><a class="nav-item nav-link btn btn-simple" href="{% url 'accounts:logout' %}">Log Out</a></li>
                {% else %}
                <li><a class="nav-item nav-link btn btn-simple" href="{% url 'posts:all' %}">Post</a></li>
                <li><a class="nav-item nav-link btn btn-simple" href="{% url 'accounts:login' %}">Log In</a></li>
                <li><a class="nav-item nav-link btn btn-simple" href="{% url 'accounts:signup' %}">Sign Up</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block content%}
        {% endblock %}
    </div>
</body>
</html>

templates/session_expired.html
{% extends 'base.html' %}
{% block content %}
    <h1>Your session has been expired.</h1>
{% endblock %}